<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="BankManagerLogin"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="0.172">
  <properties />
            <testcase name="loginAsBankManager" time="0.172" classname="testcases.BankManagerLogin">
                <failure type="java.lang.AssertionError"
                  message="Failing login test focefully"
              >
<![CDATA[java.lang.AssertionError: Failing login test focefully
  org.testng.Assert.fail(Assert.java:111)
  testcases.BankManagerLogin.loginAsBankManager(BankManagerLogin.java:19)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  java.base/java.lang.reflect.Method.invoke(Method.java:580)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
  org.testng.TestRunner.privateRun(TestRunner.java:739)
  org.testng.TestRunner.run(TestRunner.java:614)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
  org.testng.SuiteRunner.run(SuiteRunner.java:312)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
  org.testng.TestNG.runSuites(TestNG.java:1112)
  org.testng.TestNG.run(TestNG.java:1079)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
